### ISSUE TITLE
How to decode the generated dmp file

### ISSUE THREAD

**Issue by PinkyJie** [johnmuhl/electron-crash-report-server#15]
First, thank you for creating this great project, I've tried official [mini-breakpad-server](https://github.com/electron/mini-breakpad-server) but it can't work, this project works like a charm on my computer. I can see the crash report list on web page. 

My question is how to make this report human readable?

**Comment by johnmuhl** [comment]
I don't know. The dmp is just whatever electron returns to the crash reporter nothing specific to this project. You might be able to get better help from the electron/electron folks.
