### ISSUE TITLE
POST requests yield 400 bad request error

### ISSUE THREAD

**Issue by brmscheiner** [johnmuhl/electron-crash-report-server#17]
For some reason the crash reports are getting rejected by the server, but my configuration is the essentially the same as the example. Maybe there is a Heroku setting I need to change?
```
crashReporter.start({
  companyName: 'Motorized Precision',
  submitURL: 'https://motorized-precision.herokuapp.com/',
  autoSubmit: true,
  ignoreSystemCrashHandler: true,
});
```
Here is what the log says
> 2017-04-23T21:42:33.383610+00:00
> heroku[router]: at=info method=POST path="/" host=motorized-precision.herokuapp.com request_id=5b8383d2-fa4f-4a56-af36-2c90ccbf9bc4 fwd="174.237.136.28" dyno=web.1 connect=1ms service=1761ms status=400 bytes=307 protocol=https

**Comment by johnmuhl** [comment]
I'm not able to reproduce this with the demo apps or see anything obvious in the logs. What is your electron version?

You could try pointing your app at the demo server (https://pacific-falls-32011.herokuapp.com/) to at least figure out which side the error is on.

 Maybe something changed with the crash reporter recently.

**Comment by johnmuhl** [comment]
Also just in case you missed it in the readme:

> If you are not seeing crash reports after the first deploy you may need to restart the app.

"the app" meaning the heroku app.

**Comment by brmscheiner** [comment]
Hey John, thanks for the quick response! I missed that part of the readme, but I just restarted the Heroku app and the issue remains the same. I also tried pointing my crashReporter at the demo server and that didn't work, so I suppose the problem is on the electron side. I am running 
`    "electron-prebuilt": "^1.4.5",`

**Comment by johnmuhl** [comment]
Could you provide the exact electron version? I think `^1.4.5` could be anything from `1.4.5` up to `1.6.7`. I tried `1.4.16` and `1.6.7` with the demo and the reports are submitted successfully.

Is there any chance your app is open-source or you can provide a minimal app that causes the `400` response.

**Comment by brmscheiner** [comment]
Turns out I was running 1.4.13, but I just upgraded to 2.6.6 and that didn't help either.

Sadly our application is not open source, but I am working on preparing a minimal app that is ok for sharing. In the meantime, do you know of a way to examine the POST requests being sent to Heroku?

**Comment by johnmuhl** [comment]
To get more info out I'd just sprinkle some `console.log`s starting around https://github.com/johnmuhl/electron-crash-report-server/blob/master/server.js#L118 and inspect the `request` and `request.payload`.

Looking at that code it seems you are probably falling afoul of the `if (request.payload && request.payload.prod === 'Electron')` but I can't guess why you'd be missing the `payload` or why `prod` would not be `Electron`. Are you rebranding with a custom build or something that might cause one or the other to fail?

If you create a fork for debugging you should be able to deploy it to heroku using the button in the readme of your fork. Or if you have postgres setup locally you can create a database, set `DATABASE_ENV` and run `yarn start` to get a local version.

**Comment by brmscheiner** [comment]
Yup, you nailed it - prod is undefined.
```
request.payload = {"guid":"2b8b3dfc-b115-4a02-b821-e263fe327f4f", "upload_file_minidump":<Buffer 4d 44  ... >}
```
Everything works properly if I remove the check for `request.payload.prod`, although interestingly the server still responds with a status of 400. 

We are branding the app, but I can't figure out what might be causing the problem. I don't think our package.json contains anything out of the ordinary...
```
  "name": "mpstudio",
  "productName": "MPStudio",
  "version": "1.0.3",
  "private": true,
```
What is the value of checking for `request.payload.prod` in the first place?

**Comment by johnmuhl** [comment]
> Everything works properly if I remove the check for `request.payload.prod`, although interestingly the server still responds with a status of 400.

That is interesting. Can you share what the `request.payload` object looks like when that happens?
The `400` is still coming from failing the `if` part right; i.e. now `if (request.payload)` is the problem?

> What is the value of checking for `request.payload.prod` in the first place?

Just being overly cautious I guess. I would be open to removing it if that helps.

**Comment by brmscheiner** [comment]
Here is request.payload:
```
{ guid: '2b8b3dfc-b115-4a02-b821-e263fe327f4f',
2017-05-03T16:49:50.162567+00:00 app[web.1]:   upload_file_minidump: <Buffer 4d 44 4d 50 93 a7 00 00 07 00 00 00 20 00 00 00 00 00 00 00 2d 0a 0a 59 00 00 00 00 00 00 00 00 07 00 00 00 38 00 00 00 74 00 00 00 0f 00 00 00 40 03 ... > }
```
Now the response is 200, I'm not sure if I had to restart the dyno or if I misread it yesterday. So it looks like we are coming to a solution here! If you are okay with removing the check, that would work for me, but if you would like to try to figure out why prod is missing for me I would be more than happy to help out. Maybe it's an OS thing? I'm OS X 10.12.4

**Comment by brmscheiner** [comment]
Actually, taking another look at the request.payload in the demo it seems like I am missing a lot of properties, not just prod... ver, extra, platform, _productName, _productName, process_type. I am trying to send a lot of this information in crashReporter.start 
```
crashReporter.start({
  productName: 'MPStudio',
  companyName: 'Motorized Precision',
  submitURL: 'https://motorized-precision.herokuapp.com/',
  autoSubmit: true,
  ignoreSystemCrashHandler: false,
  extra: {'test': 'test'}
});
```

**Comment by johnmuhl** [comment]
Just to be a bit more certain the problem here relates to rebranding and is not a platform issue could you use the `electron-bomb` app (`cd electron-bomb && yarn && yarn start`) in this repo (or start from the [`electron-quick-start`](https://github.com/electron/electron-quick-start and connect the crash reporter server) and ensure that works on your system.

> but if you would like to try to figure out why prod is missing for me I would be more than happy to help out. Maybe it's an OS thing? I'm OS X 10.12.4

I'm interested in why your request is missing most of the [default properties](https://electron.atom.io/docs/api/crash-reporter/#crash-report-payload). If the above sanity-check fails and you have the time to create a minimal reproduction that is likely to be the most helpful way forward.

**Comment by brmscheiner** [comment]
So I cloned electron-quick-start and reported a crash to each of our servers and the same default properties were missing. Here is the [report](https://pacific-falls-32011.herokuapp.com/reports/16) on your server. 

Perhaps the correct course of action is to close this issue and open one with electron. What do you think?

**Comment by johnmuhl** [comment]
> Perhaps the correct course of action is to close this issue and open one with electron. What do you think?

Sounds good. If any new information warrants re-opening feel free to do so and we can pick it up there.

**Comment by brmscheiner** [comment]
Thanks for the help!
