### ISSUE TITLE
deploy on herokuapp error

### ISSUE THREAD

**Issue by dipenpatel235** [johnmuhl/electron-crash-report-server#18]
hello 
i am not able to deploy herokuapp 
i have already changed username and password 
getting below error
Item could not be created:
please contact to support

**Comment by johnmuhl** [comment]
I think it is a Heroku problem. When I try to use the deploy button the following ends up in the browser console.

~~~
XMLHttpRequest cannot load https://api.heroku.com/app-setups. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dashboard.heroku.com' is therefore not allowed access.
~~~

Hopefully they're already aware and working on a fix. In the meantime you can `git clone` the repo to your computer and deploy manually.

**Comment by dipenpatel235** [comment]
deploy manually how ?
i have already clone git code
then did below command

cd /root/electron-crash-report-server
npm install
npm start

gettting below error
{ Error: ENOENT: no such file or directory, open '.env'

**Comment by johnmuhl** [comment]
> deploy manually how ?

Assuming you have your Heroku account and the command line tools setup locally:

~~~
git clone johnmuhl/electron-crash-report-server
cd electron-crash-report-server
heroku apps:create
heroku addons:create heroku-postgresql:hobby-dev
heroku config:set AUTH_USER=crash
heroku config:set AUTH_PASS=electron
git push heroku master
~~~

Check out https://devcenter.heroku.com/articles/git if you're not familiar with Heroku deployment.

`electron-crash-report-server` should deploy like any other Heroku compatible app.

> { Error: ENOENT: no such file or directory, open '.env'

Sorry that running locally isn't documented. You need to create the `.env` in the root of the project; e.g.

~~~
AUTH_USER=crash
AUTH_PASS=electron
DATABASE_URL=postgres://localhost/electron-crash-report-server
PORT=0
~~~

and you'll need PostgreSQL setup and to run `createdb electron-crash-report-server`.

**Comment by johnmuhl** [comment]
@dipenpatel235 Can you confirm that you get the same (or similar) error in your browser console as I did above?

> XMLHttpRequest cannot load https://api.heroku.com/app-setups. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://dashboard.heroku.com' is therefore not allowed access.

**Comment by johnmuhl** [comment]
Despite the errors messages the application is actually created and works as expected. @dipenpatel235 if you check your Heroku dashboard do you see any new applications?

**Comment by johnmuhl** [comment]
Should be working now https://status.heroku.com/incidents/1158

**Comment by dipenpatel235** [comment]
@dipenpatel235 Can you confirm that you get the same (or similar) error in your browser console as I did above?
-Yes.

Now i have done all steps and connected but getting below error from postgresql database 

[root@spare electron-crash-report-server]# npm start

> electron-crash-report-server@0.5.1 start /root/electron-crash-report-server
> node server.js

Server running at: http://spare.host.com:35886
/root/electron-crash-report-server/db.js:12
  if (err) throw err
           ^

Error: syntax error at or near "NOT"
    at Massive.DB.query (/root/electron-crash-report-server/node_modules/massive/lib/runner.js:22:11)
    at Massive.run (/root/electron-crash-report-server/node_modules/massive/index.js:86:8)
    at Object.<anonymous> (/root/electron-crash-report-server/db.js:11:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! electron-crash-report-server@0.5.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-crash-report-server@0.5.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-crash-report-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-crash-report-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-crash-report-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/electron-crash-report-server/npm-debug.log

**Comment by johnmuhl** [comment]
The deploy to Heroku button should be working now; if it is not please open a support ticket with Heroku. 

If you are having issues unrelated to the Heroku button please open a different issue.
