### ISSUE TITLE
Error: syntax error at or near "NOT"

### ISSUE THREAD

**Issue by dipenpatel235** [johnmuhl/electron-crash-report-server#19]
postgres (PostgreSQL) 9.2.18
Centos 7 64 bit

[root@spare electron-crash-report-server]# npm start

electron-crash-report-server@0.5.1 start /root/electron-crash-report-server
node server.js
Server running at: http://spare.host.com:35886
/root/electron-crash-report-server/db.js:12
if (err) throw err
^

Error: syntax error at or near "NOT"
at Massive.DB.query (/root/electron-crash-report-server/node_modules/massive/lib/runner.js:22:11)
at Massive.run (/root/electron-crash-report-server/node_modules/massive/index.js:86:8)
at Object. (/root/electron-crash-report-server/db.js:11:4)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

npm ERR! Linux 3.10.0-514.16.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.10.1
npm ERR! npm v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! electron-crash-report-server@0.5.1 start: node server.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-crash-report-server@0.5.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-crash-report-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs electron-crash-report-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls electron-crash-report-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /root/electron-crash-report-server/npm-debug.log

**Comment by johnmuhl** [comment]
Minimum supported PostgreSQL is version 9.4 due to use of `jsonb` type.
