### ISSUE TITLE
Add option to send email

### ISSUE THREAD

**Issue by johnmuhl** [johnmuhl/electron-crash-report-server#291]
@Bioswami-nfac Beyond SMTP settings and the `to` address what else do you need to configure? A custom `subject` or `body` or anything else?

Refs: #290

**Comment by Bioswami-nfac** [comment]
Custom Subject. Option to Add specific values to the Subject. Example a username etc.
Custom Body would be nice but even if you can give all the payload in that, it would suffice.
Attachment of stack-trace as a file.
