### ISSUE TITLE
Add support to automatically generate Github/Gitlab issues

### ISSUE THREAD

**Issue by jhotujec** [johnmuhl/electron-crash-report-server#47]
This is just an idea, but it would be good to have some sort of automatic issue generation when new dump is posted to the server.

**Comment by johnmuhl** [comment]
I thought about that before and decided syncing between GitHub and the ECRS database was more pain than the feature was worth.

Maybe a "send to GitHub" option could skip the ECRS database completely and just post the relevant information to GH. Essentially reducing the server to just the `POST /` route handler and removing the need to sync between the two.

**Comment by johnmuhl** [comment]
Another question is how to deal with many apps reporting to the same ECRS. I guess you could setup a `org/crashes` repo or something but now we need to label incoming reports with the app somehow.

**Comment by jhotujec** [comment]
I would say avoiding the database and just using plain `POST`request should be enough. As long as we provide a link to the dump on the ECRS I'm thinking it should be fine. We can try implementing it without multiple-app support in mind and add it latter, especially if we won't need to think about the database design, since we won't have one.

I'm not sure if this issue is a priority(probably not) but I'm thinking of using this repo in the production so this is a real-world feedback :)

**Comment by johnmuhl** [comment]
Dump files are stored as blobs in the database because Heroku has no permanent storage but I think the dump file could probably be attached to the GH issue directly; the stack trace provided by `minidump` as well.

It is an interesting feature for sure. If you want to work on it let me know or just open a PR we can look at.  Otherwise I'll put it in the queue.

**Comment by jhotujec** [comment]
I think it's not a pending issue, but it would be cool to have it implemented one day. Not sure how much time will I have, maybe :)
