### ISSUE TITLE
Improve browser support

### ISSUE THREAD

**Issue by johnmuhl** [johnmuhl/electron-crash-report-server#48]
Only the latest version of Chrome, Edge and Safari are supported; Firefox is supported if the user enables JavaScript module support in `about:config`. In #43 it was brought up that this is not good enough.

> I get your point regarding Firefox, but currently market share for Firefox browser is around 13% which is 
> quite a lot.

Fair enough. As a Firefox user I struggled with this when I made the decision. I made the choice to enable the setting and use the feature in order to provide real world feedback should I find anything useful in the exercise; I didn't and likely won't. Lets just go back to compiling for now.

> Opera Mini

Even on mobile browsers that support all the latest features the experience is terrible but I want to improve it. 

> IE11

I'm not concerned about any version of IE. The app has never supported IE and in 2 years there have been no requests to add it.

> Does that mean that all of those people aren't gonna be able to see the application?

Yes; but the users in this case are developers of Electron apps; I assume they mostly use modern (if not evergreen) browsers. Maybe when more people start using v1 the outcry will come but so far so good.

---

@jhotujec considering the audience what do you think is a reasonable baseline for browser support? I feel that "last 2 {Chrome, Edge, Firefox, Safari} versions" is a good start.

**Comment by jhotujec** [comment]
All and all I think your point about end users being developers is valid and I wouldn't overthink this right now. I guess we can leave it as is for now.

**Comment by jhotujec** [comment]
<img width="1271" alt="screen shot 2018-01-17 at 01 50 42" src="https://user-images.githubusercontent.com/784318/35019795-125ee758-fb29-11e7-8afd-40290170aa7e.png">

I'm confirming that Safari also works ok :)
